---
title: "Single Trait GBLUP"
author: "Ye Bi"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
setwd("~/Library/CloudStorage/OneDrive-VirginiaTech/Research/Codes/research/RiceUNLMetabolites/GBLUP4Met/Githubs/GBLUP4Met")
library(tidyverse)
library(ggplot2)
library(plyr)
library(ggpubr)
library(ggrepel)
library(tidyverse)
library(stargazer)
library(patchwork)
library(ggplot2)
```

## Drawing plots for h2, varE, varG
```{r}
source("../Functions/functions.R")
met_names = met_name_func(mode = 'name')
```

##Loading pred corr 
```{r}
path.bglr_subpop = "~/Library/CloudStorage/OneDrive-VirginiaTech/Research/Codes/research/RiceUNLMetabolites/GBLUP4Met/outputs/GBLUP_subpopulation"

load_pred_corr_func_subpop <- function(path, namm, kernel){
  PredCorr_conL <- list()
  PredCorr_trtL <- list()
  nCV = 4
  for (i in 1:nCV){
    PredCorr_conL[[i]] <- readRDS(file=file.path(path,paste0("Control_",namm,"cv_",i,".RDS")))
    PredCorr_trtL[[i]] <- readRDS(file=file.path(path,paste0("Stress_",namm,"cv_",i,".RDS")))
  }
  
  corr.c.df <- do.call(rbind, PredCorr_conL)
  corr.c.df = corr.c.df[,1:66]
  colnames(corr.c.df)= met_names
  
  corr.t.df <- do.call(rbind, PredCorr_trtL)
  corr.t.df = corr.t.df[,1:66]
  colnames(corr.t.df) = met_names
  
  temp1 <- reshape2::melt(corr.c.df)
  temp2 <- reshape2::melt(corr.t.df)
  temp3 <- rbind.data.frame(temp1,temp2)
  temp3$group <- rep(c("Control", "Stress"), each = 66*nCV)
  colnames(temp3) <- c("CV", "Met", "Corr", "Treatment")
  temp3$Kernel = kernel
  temp3$Met = factor(temp3$Met, levels = met_names)
  temp3 = temp3 %>% arrange(CV, Treatment)
  
  return(temp3)
}


PreCorr_subpop = load_pred_corr_func_subpop(path=path.bglr_subpop, kernel = "subpop", namm='bglr_')

PreCorr_subpop$CV = as.factor(PreCorr_subpop$CV)
subss = tools::toTitleCase(c('aus', 'indica', 'temperate-japonica', 'tropical-japonica'))
for(i in 1:4){
PreCorr_subpop$CV = gsub(i, subss[i], PreCorr_subpop$CV)
}
```


# ######Scatterplot for PredCorr_subpop
```{r}
library(plyr)

df = PreCorr_subpop
mu <- ddply(df, "Treatment", summarise, corr.mean=mean(Corr, na.rm=T))
head(mu)

my_colors <- RColorBrewer::brewer.pal(8, "Dark2")[5:8]


Pred_Cor_boxplot <- ggplot(df, aes(x=Met, y=Corr), color = CV, fill = CV) + 
           facet_grid(rows = vars(Treatment))+
           geom_point(aes(fill=CV, color = CV))+
           labs(x="Metabolite accumulation", y = "Prediction accuracy") +
           theme_bw()+
           # geom_hline(data=mu, aes(yintercept=corr.mean, color=Treatment), linetype='solid', linewidth = 1)+
           scale_y_continuous(limits=c(-0.5, 0.65), breaks=seq(-0.5,0.7,0.2)) +
           scale_fill_manual(values = ggplot2::alpha(my_colors, 0.7))+
           scale_color_manual(values = my_colors)+
          # scale_color_brewer(palette = "Dark2")+
           theme(axis.text.x=element_text(size=8, angle=90, hjust=0.95, vjust=0.2),
                 axis.text.y=element_text(size=8))+
          labs(fill = "Subpopulation predicted", color = "Subpopulation predicted") 

Pred_Cor_boxplot
dev.print(pdf, file="../../../temp/subpopulation_gblup.pdf", height = 6, width = 10)
```

## Calculate difference between subpop with single-trait GBLUP
```{r}
BGLR_G_mu <- pred_mean_generator(PreCorr)


PreCorr_subpop_L <- PreCorr_subpop %>% group_split(CV)
names(PreCorr_subpop_L) <- unique(PreCorr_subpop$CV)

subpop_G_mu_L <- lapply(PreCorr_subpop_L, pred_mean_generator)
```


```{r}
dff_sub_g_L = list()
for (i in 1:length(subpop_G_mu_L)){

  dff_sub_g_L[[i]]=pred_dff_generator(df1=BGLR_G_mu, 
                   df2=subpop_G_mu_L[[i]], 
                   Method=paste0(names(subpop_G_mu_L)[i]))
}
names(dff_sub_g_L) = names(subpop_G_mu_L)

dff_sub_g = do.call(rbind, dff_sub_g_L)

df = dff_sub_g

```


```{r}
library(ggplot2)
library(RColorBrewer)

# Define colors
my_colors <- RColorBrewer::brewer.pal(8, "Dark2")[5:8]

# Ensure Method is a factor
df$Method <- as.factor(df$Method)

Pred_Cor_boxplot <- ggplot(df, aes(x=Met, y=value), color = Method, fill = Method) + 
           facet_grid(rows = vars(Treatment))+
           geom_point(aes(fill=Method, color = Method))+
           geom_hline(aes(yintercept = 0), color = 'lightcoral', linetype = 'solid', linewidth = 0.5, alpha = 0.7) + 
           scale_y_continuous(limits=c(-1000,600)) +
           scale_fill_manual(values = ggplot2::alpha(my_colors, 0.7))+
           scale_color_manual(values = my_colors)+
           labs(x="Metabolite accumulation", y = "Prediction difference (%)") +
           theme_bw()+
           theme(axis.text.x=element_text(size=8, angle=90, hjust=0.95, vjust=0.2),
                 axis.text.y=element_text(size=8))+
          labs(fill = "Subpopulation prediction", color = "Subpopulation prediction") 
# Print the plot
print(Pred_Cor_boxplot)
dev.print(pdf, file="../../../temp/subpopulation_gblup_difference.pdf", height = 6, width = 10)
# 
```




