---
title: "GK"
author: "Ye Bi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#loading packages
```{r, message=F}
library(tidyverse)
library(lme4)
library(readxl)
```

```{r}
source("../../Functions/functions.R")
```


###################################
##### Generate GK kernels.
###################################
#load SNPs
```{r}
## Read into met.rr dataset to get NSFTV_ID in treatments.
met_rr_stress <- read.csv("../../../Met/met_rr_stress.csv")
met_rr_control <- read.csv("../../../Met/met_rr_control.csv")
id_control <- met_rr_control$NSFTV_ID #162
id_stress <- met_rr_stress$NSFTV_ID #162

load("../../../Geno/geno.rr.RData")
geno <- geno_rr
geno_control = geno[id_control, ]
geno_stress = geno[id_stress, ] 
Xcs_control = scale(geno_control, center = T, scale = T)
Xcs_stress = scale(geno_stress, center = T, scale = T)
XcsL = list(Control = Xcs_control,
            Stress = Xcs_stress)
# save(XcsL, file="../Geno/XcsL.RData")

#GBLUP Gmatrix
G_control = tcrossprod(Xcs_control)/ncol(Xcs_control)
G_stress = tcrossprod(Xcs_stress)/ncol(Xcs_stress)
```

#Draw histogram for G matrix
```{r}
hist_draw_func <- function(GK, mainn){
  hist(GK[upper.tri(GK)], main=mainn)
}
```

#Histogram for Gmatrix
```{r}
hist_draw_func(GK = G_control, mainn = 'G_control')
hist_draw_func(GK = G_stress, mainn = 'G_stress')
```

#Build Hauclidean distance matrix 
```{r}
treatment = "Control"
treatment = "Stress"
Xcs <- XcsL[[treatment]]
D<- as.matrix(dist(Xcs, method="euclidean"))^2
Dmean <- D/mean(D)
Dmean_control = Dmean
Dmean_stress = Dmean
```

#Build Gaussian Kernel
```{r}
computeGK_func<- function(bw, Dmean){
  GK <- exp(-bw * Dmean) 
  return(GK)
}
```
```{r}
GK0.25_stress <- computeGK_func(bw=0.25, Dmean = Dmean_stress)
GK0.25_control = GK0.25_stress
hist_draw_func(GK0.25_stress, "GK0.25_stress")
mean(GK0.25_stress[upper.tri(GK0.25_stress)])

GK1.5_stress <- computeGK_func(bw=1.5, Dmean = Dmean_stress)
GK1.5_control = GK1.5_stress
hist_draw_func(GK1.5_stress, "GK1.5_stress")
mean(GK1.5_stress[upper.tri(GK1.5_stress)])

GKL = list(Control = list(GK0.25 = GK0.25_control,
                          GK1.5 = GK1.5_control),
           Stress = list(GK0.25 = GK0.25_stress,
                          GK1.5 = GK1.5_stress))

# save(GKL, file = "../Geno/GKL.RData")
```
